server:
  port: 8082
  servlet:
    context-path: /catalogo

spring:
  application:
    name: catalogo
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/catalogo
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

catalogo:
  rabbitmq:
    exchange: catalogo.exchange
    routingkey: catalogo.produto.routingkey

security:
  jwt:
    token:
      secret-key: chave_microservices

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka
